### PR TITLE
take down EOL 4.9 status

### PR DESCRIPTION
**Pull request by nickdesaulniers**

### CODE REVIEW

**Review by nathanchance — APPROVED** [review]
LGTM. I think we might be missing an Android tree but I did not look to closely. This obviously makes sense regardless.

**Comment by nickdesaulniers** [comment]
I think we're still building the android 4.9 trees?
https://github.com/clangbuiltlinux/continuous-integration2/actions/workflows/android-4.9-clang-16.yml
shows it ran 12 hrs ago.

We probably should stop those builds, too?

**Comment by nathanchance** [comment]
> I think we're still building the android 4.9 trees?
> 
> https://github.com/clangbuiltlinux/continuous-integration2/actions/workflows/android-4.9-clang-16.yml
> 
> shows it ran 12 hrs ago.
> 
> 
> 
> We probably should stop those builds, too?

Yes, good point, it seems I missed the Android 4.9 builds for my PR :/

**Comment by nickdesaulniers** [comment]
Ok, I've added a commit on top for the android 4.9 status; I'll send the patch actually disabling the builds in CI next.

**Pull request merged**
