### PR TITLE
add links to public calendar and hangouts

### PR DESCRIPTION
**Pull request by nickdesaulniers**
this was an internal to Google meeting that we were having once every two weeks.

@eiais asked "why don't we make this meeting publicly accessible?"

Boom. Done. cc folks for visibility if they're interested.

### CODE REVIEW

**Comment by nathanchance** [comment]
Awesome! I don't know if it's me but when I open that link, it says requested event not found. Might be some jank on my end though.

**Comment by kbeyls** [comment]
> Awesome! I don't know if it's me but when I open that link, it says requested event not found. Might be some jank on my end though.

I see a similar message: event not found, when I follow the link.

**Comment by nickdesaulniers** [comment]
sorry, I've been monkeying around with the calendar invite; I suppose each change to the event produces a new link.  Hopefully not, but let me check if that's the issue.

**Comment by nickdesaulniers** [comment]
@kbeyls can you triple now? I think it should be good to go.

**Comment by kbeyls** [comment]
> @kbeyls can you triple check now? I think it should be good to go.

The link works for me now. Thanks!

**Pull request merged**
